apiVersion: v1
name: fitness-center-weekly
description: fitness center weekly mailer
type: application
version: 0.1.3
appVersion: 1.8.5
icon: file://../logo.png
sources:
  - https://github.com/BuildingLink/charts
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com

