sreplicaCount: 1

image:
  repository: buildinglink/fitnessweekly
  pullPolicy: IfNotPresent
  tag: "1.8.5"
env:
  open:
    # storage backend, can be one of: local, alibaba, amazon, google, microsoft
    STORAGE: local

