replicaCount: 1

env:
  open:
    BLDBPRO: aware
    BLRANCHER: https://rancher.buildinglink.com
image:
  repository: buildinglink/fitnessweekly
  pullPolicy: IfNotPresent
  tag: "1.8.5"
service:
  port: 3000  