apiVersion: v1
name: priority-mailer
description: Buildinglink priority email service
type: application
version: 0.1.2
appVersion: 1.0.0
icon: file://../logo.png
keywords:
  - buildinglink
  - mailers
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com

