apiVersion: v
name: mailer-services
description: Buildinglink Mailer Services Reimagined
type: application
version: 0.1.9
appVersion: 1.0.0
icon: file://../logo.png
keywords:
  - buildinglink
  - mailers
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com
