apiVersion: v1
name: attachment-mailer
description: Buildinglink attachment email service
type: application
version: 0.1.0
appVersion: 1.0.0
icon: file://../logo.png
keywords:
  - buildinglink
  - mailers
maintainers:
  - name: buildinglink  
    email: charts@buildinglink.com

