name: cert-manager
version: v0.3.2
appVersion: v0.3.0
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/jetstack/cert-manager
icon: file://../logo.png
maintainers:
  - name: Marc J. Greenberg
    email: marc@buildinglink.com
